# Generated by Django 5.2.17 on 2026-09-14 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('development_status', models.CharField(choices=[('in_development', 'In Development'), ('released', 'Released')], default='in_development', max_length=32)),
                ('maintenance_status', models.CharField(choices=[('deprecated', 'No Longer Maintained'), ('maintained', 'Updated & Maintained')], default='maintained', max_length=32)),
            ],
        ),
    ]
